name: CI

on:
  push:
    branches:
      - master

jobs:
  deploy-on-render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Yarn install BE
        run: yarn

      - name: Yarn Install and Build FE
        run: |
          cd client
          yarn
          yarn run build

      - name: Lint
        run: |
          cd client
          yarn lint .

      - name: Deploy to Render.com
        run: echo "Follow deployment on Render.com https://dashboard.render.com/"
